{{- range $index, $machineClass := .Values.machineClasses }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $machineClass.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    garden.sapcloud.io/purpose: machineclass
type: Opaque
data:
  userData: {{ $machineClass.secret.cloudConfig | b64enc }}
  azureClientId: {{ $machineClass.secret.clientID | b64enc }}
  azureClientSecret: {{ $machineClass.secret.clientSecret | b64enc }}
  azureSubscriptionId: {{ $machineClass.secret.subscriptionID | b64enc }}
  azureTenantId: {{ $machineClass.secret.tenantID | b64enc }}
---
apiVersion: machine.sapcloud.io/v1alpha1
kind: AzureMachineClass
metadata:
  name: {{ $machineClass.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  location: {{ $machineClass.region }}
  properties:
    {{- if hasKey $machineClass "zone" }}
    zone: {{ $machineClass.zone }}
    {{- end }}
    {{- if hasKey $machineClass "availabilitySetID" }}
    availabilitySet:
      id: {{ $machineClass.availabilitySetID }}
    {{- end }}
    hardwareProfile:
      vmSize: {{ $machineClass.machineType }}
    osProfile:
      adminUsername: core
      linuxConfiguration:
        disablePasswordAuthentication: true
        ssh:
          publicKeys:
            path: /home/core/.ssh/authorized_keys
            keyData: {{ $machineClass.sshPublicKey }}
    storageProfile:
      imageReference:
        publisher: {{ $machineClass.image.publisher }} # TODO: remove this deprecated field after couple of releases
        offer: {{ $machineClass.image.offer }} # TODO: remove this deprecated field after couple of releases
        sku: {{ $machineClass.image.sku }} # TODO: remove this deprecated field after couple of releases
        version: {{ $machineClass.image.version }} # TODO: remove this deprecated field after couple of releases
        urn: {{ $machineClass.image.urn }}
      osDisk:
        caching: None
        diskSizeGB: {{ $machineClass.volumeSize }}
        createOption: FromImage
  resourceGroup: {{ $machineClass.resourceGroup }}
  secretRef:
    name: {{ $machineClass.name }}
    namespace: {{ $.Release.Namespace }}
  subnetInfo:
    vnetName: {{ $machineClass.vnetName }}
    subnetName: {{ $machineClass.subnetName }}
{{- if $machineClass.tags }}
  tags:
{{ toYaml $machineClass.tags | indent 4 }}
{{- end }}
{{- end }}
