google:
  project: my-project
  region: eu-west-1

create:
  vpc: true

vpc:
  name: ${google_compute_network.network.name}

clusterName: test-namespace

networks:
  services: 100.64.0.0/13
  pods: 100.96.0.0/11
  worker: 10.250.0.0/19
#  internal: 10.250.112.0/22
  flowLogs:
    enableFlowLogs: "true"
    aggregationInterval: "INTERVAL_10_MIN"
    flowSampling: 0.5
    metadata: "INCLUDE_ALL_METADATA"

outputKeys:
  vpcName: vpc_name
  subnetNodes: subnet_nodes
  serviceAccountEmail: service_account_email
  subnetInternal: subnet_internal