apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-provider-kubelet-config
  namespace: {{ .Release.Namespace }}
data:
  cloudprovider.conf: |
    {{- include "cloud-provider-config" .  | indent 4}}
    {{- if semverCompare "< 1.15" .Values.kubernetesVersion }}
    {{- include "azure-credentials" .   | indent 4 }}
    {{- else }}
    useInstanceMetadata: true
    {{- end}}
