---
apiVersion: alicloud.provider.extensions.config.gardener.cloud/v1alpha1
kind: ControllerConfiguration
clientConnection:
  acceptContentTypes: application/json
  contentType: application/json
  qps: 100
  burst: 130
machineImages:
- name: coreos-alicloud
  version: 2023.4.0
  id: coreos_2023_4_0_64_30G_alibase_20190319.vhd
etcd:
  storage:
    className: gardener.cloud-fast
    capacity: 25Gi
  backup:
    schedule: "0 */24 * * *"
