---
apiVersion: v1
kind: Secret
metadata:
  name: cloudprovider
  namespace: shoot--foobar--alicloud
type: Opaque
data:
  accessKeyID: AAAA # base64(accessKeyID)
  accessKeySecret: AAAA # base64(accessKeySecret)
---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: Cluster
metadata:
  name: shoot--foobar--alicloud
spec:
  cloudProfile:
    apiVersion: core.gardener.cloud/v1alpha1
    kind: CloudProfile
  seed:
    apiVersion: core.gardener.cloud/v1alpha1
    kind: Seed
  shoot:
    apiVersion: core.gardener.cloud/v1alpha1
    kind: Shoot
    spec:
      kubernetes:
        version: 1.13.4
    status:
      lastOperation:
        state: Succeeded
---
# This resource does result in the deployment of the machine-controller-manager, the machine classes,
# and the desired MachineDeployments. However, it does not create actual virtual machines because the
# needed infrastructure does probably not exist.
apiVersion: extensions.gardener.cloud/v1alpha1
kind: Worker
metadata:
  name: worker
  namespace: shoot--foobar--alicloud
spec:
  type: alicloud
  region: cn-beijing
  secretRef:
    name: cloudprovider
    namespace: shoot--foobar--alicloud
  infrastructureProviderStatus:
    apiVersion: alicloud.provider.extensions.gardener.cloud/v1alpha1
    kind: InfrastructureStatus
    vpc:
      cidr: 10.250.0.0/16
      id: vpc-gw879zodzt6z1cupe3ps4
    keyPairName: shoot--foobar--alicloud-ssh-publickey
    securityGroupId: sg-gw8efawapk7dhq6q5z24
  pools:
  - name: cpu-worker
    machineType: ecs.sn2ne.xlarge
    machineImage:
      name: coreos
      version: 2023.5.0
    minimum: 1
    maximum: 1
    maxSurge: 1
    maxUnavailable: 0
  # labels:
  #   key: value
  # annotations:
  #   key: value
  # taints: # See also https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  # - key: foo
  #   value: bar
  #   effect: NoSchedule
    userData: IyEvYmluL2Jhc2gKCmVjaG8gImhlbGxvIHdvcmxkIgo=
    volume:
      type: cloud_efficiency
      size: 30Gi
    zones:
    - cn-beijing-f
