---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: extensions.gardener.cloud:{{ .Values.serviceName }}:shoot-services
  labels:
    app.kubernetes.io/name: gardener-extension-{{ .Values.serviceName }}
    helm.sh/chart: gardener-extension-{{ .Values.serviceName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
rules:
- apiGroups:
    - dns.gardener.cloud
  resources:
    - dnsentries
    - dnsentries/status
  verbs:
    - get
    - list
    - update
    - watch
    - create
    - delete
