---
apiVersion: {{ include "storageclassversion" . }}
kind: StorageClass
metadata:
  name: managed-standard-hdd
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standard_LRS
  kind: managed