{{- if semverCompare ">= 1.13" .Capabilities.KubeVersion.GitVersion }}
---
apiVersion: {{ include "storageclassversion" . }}
kind: StorageClass
metadata:
  name: managed-standard-ssd
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: StandardSSD_LRS
  kind: managed
{{- end}}