---
apiVersion: {{ include "storageclassversion" . }}
kind: StorageClass
metadata:
  name: default
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standard_LRS
  kind: managed
---
apiVersion: {{ include "storageclassversion" . }}
kind: StorageClass
metadata:
  name: managed-standard-hdd
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standard_LRS
  kind: managed
---
apiVersion: {{ include "storageclassversion" . }}
kind: StorageClass
metadata:
  name: managed-premium-ssd
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Premium_LRS
  kind: managed
---
apiVersion: {{ include "storageclassversion" . }}
kind: StorageClass
metadata:
  name: files
provisioner: kubernetes.io/azure-file
parameters:
  skuName: Standard_LRS
