---
apiVersion: {{ include "storageclassversion" . }}
kind: StorageClass
metadata:
  name: default
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard

---
apiVersion: {{ include "storageclassversion" . }}
kind: StorageClass
metadata:
  name: gce-sc-fast
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
