---
apiVersion: azure.provider.extensions.config.gardener.cloud/v1alpha1
kind: ControllerConfiguration
clientConnection:
  acceptContentTypes: application/json
  contentType: application/json
  qps: 100
  burst: 130
machineImages:
- name: coreos
  version: 2135.6.0
  publisher: CoreOS # TODO: remove these deprecated field after couple of releases
  offer: CoreOS # TODO: remove these deprecated field after couple of releases
  sku: Stable # TODO: remove these deprecated field after couple of releases
  urn: "CoreOS:CoreOS:Stable:2135.6.0"
etcd:
  storage:
    className: gardener.cloud-fast
    capacity: 33Gi
  backup:
    schedule: "0 */24 * * *"
