---
apiVersion: v1
kind: Secret
metadata:
  name: backupprovider
  namespace: garden
type: Opaque
data:
# storageAccount: base64(storageAccount)
# storageKey: base64(storageKey)
---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: BackupBucket
metadata:
  name: cloud--azure--fg2d6
spec:
  type: azure
  region: eu-west-1
  secretRef:
    name: backupprovider
    namespace: garden