---
apiVersion: v1
kind: Secret
metadata:
  name: backupprovider
  namespace: shoot--foobar--azure
type: Opaque
data:
# storageAccount: base64(storageAccount)
# storageKey: base64(storageKey)
---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: BackupEntry
metadata:
  name: shoot--foobar--azure--sd34f
spec:
  type: azure
  region: eu-west-1
  bucketName: cloud--azure--fg2d6
  secretRef:
    name: backupprovider
    namespace: garden
