---
apiVersion: v1
kind: Namespace
metadata:
  name: shoot--foobar--azure
---
apiVersion: v1
kind: Secret
metadata:
  namespace: shoot--foobar--azure
  name: core-azure
type: Opaque
data:
# clientID: base64(clientID)
# clientSecret: base64(clientSecret)
# subscriptionID: base64(subscriptionID)
# tenantID: base64(tenantID)
---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: Cluster
metadata:
  name: shoot--foobar--azure
spec:
  cloudProfile:
    apiVersion: garden.sapcloud.io/v1beta1
    kind: CloudProfile
    spec:
      azure:
        countFaultDomains:
        - count: 2
          region: westeurope
        countUpdateDomains:
        - count: 5
          region: westeurope
  seed:
    apiVersion: garden.sapcloud.io/v1beta1
    kind: Seed
  shoot:
    apiVersion: garden.sapcloud.io/v1beta1
    kind: Shoot
    spec:
      cloud:
        azure:
          networks:
            pods: 10.243.128.0/17
            services: 10.243.0.0/17
    status:
      lastOperation:
        state: Succeeded
---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: Infrastructure
metadata:
  namespace: shoot--foobar--azure
  name: azure-infra
spec:
  type: azure
  region: westeurope
  secretRef:
    namespace: shoot--foobar--azure
    name: core-azure
  providerConfig:
    apiVersion: azure.provider.extensions.gardener.cloud/v1alpha1
    kind: InfrastructureConfig
    networks:
      vnet: # specify either 'name' or 'cidr'
      # name: my-vnet
        cidr: 10.250.0.0/16
      workers: 10.250.0.0/19
  # resourceGroup:
  #   name: mygroup
