{{- range $index, $machineClass := .Values.machineClasses }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $machineClass.name }}
  namespace: {{ $.Release.Namespace }}
{{- if $machineClass.labels }}
  labels:
{{ toYaml $machineClass.labels | indent 4 }}
{{- end }}
type: Opaque
data:
  userData: {{ $machineClass.secret.cloudConfig | b64enc }}
  apiToken: {{ $machineClass.secret.apiToken | b64enc }}
---
apiVersion: machine.sapcloud.io/v1alpha1
kind: PacketMachineClass
metadata:
  name: {{ $machineClass.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  projectID: {{ $machineClass.projectID }}
  OS: {{ $machineClass.OS }}
  billingCycle: {{ $machineClass.billingCycle }}
  machineType: {{ $machineClass.machineType }}
  sshKeys:
{{ toYaml $machineClass.sshKeys | indent 4 }}
{{- if $machineClass.metadata }}
  metadata:
{{ toYaml $machineClass.metadata | indent 2 }}
{{- end }}
  secretRef:
    name: {{ $machineClass.name }}
    namespace: {{ $.Release.Namespace }}
{{- if $machineClass.tags }}
  tags:
{{ toYaml $machineClass.tags | indent 4 }}
{{- end }}
  facility:
{{ toYaml $machineClass.facility | indent 2 }}
{{- end }}
