apiVersion: apps/v1
kind: Deployment
metadata:
  name: gardener-extension-networking-calico
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: gardener-extension-networking-calico
    helm.sh/chart: gardener-extension-networking-calico
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  revisionHistoryLimit: 0
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: gardener-extension-networking-calico
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gardener-extension-networking-calico
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: gardener-extension-networking-calico
      containers:
      - name: gardener-extension-networking-calico
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - /gardener-extension-hyper
        - networking-calico-controller-manager
        - --max-concurrent-reconciles={{ .Values.concurrentSyncs }}
        - --disable-controllers={{ .Values.disableControllers | join "," }}
        env:
        - name: LEADER_ELECTION_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
{{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | nindent 10 }}
{{- end }}