apiVersion: v1
kind: ServiceAccount
metadata:
  name: gardener-extension-networking-calico
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: gardener-extension-networking-calico
    helm.sh/chart: gardener-extension-networking-calico
    app.kubernetes.io/instance: {{ .Release.Name }}